"""Added yc tables + updated user fields

Revision ID: 61d1928de416
Revises: 00d22dc06e9a
Create Date: 2026-02-10 10:40:59.927181

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61d1928de416'
down_revision = '00d22dc06e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yccompany',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('yc_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('batch', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('batch_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('subindustry', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('all_locations', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('one_liner', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('long_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('small_logo_thumb_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('is_hiring', sa.Boolean(), nullable=False),
    sa.Column('nonprofit', sa.Boolean(), nullable=False),
    sa.Column('top_company', sa.Boolean(), nullable=False),
    sa.Column('industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('launched_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yccompany_batch'), 'yccompany', ['batch'], unique=False)
    op.create_index(op.f('ix_yccompany_batch_code'), 'yccompany', ['batch_code'], unique=False)
    op.create_index(op.f('ix_yccompany_created_at'), 'yccompany', ['created_at'], unique=False)
    op.create_index(op.f('ix_yccompany_industry'), 'yccompany', ['industry'], unique=False)
    op.create_index(op.f('ix_yccompany_is_hiring'), 'yccompany', ['is_hiring'], unique=False)
    op.create_index(op.f('ix_yccompany_launched_at'), 'yccompany', ['launched_at'], unique=False)
    op.create_index(op.f('ix_yccompany_name'), 'yccompany', ['name'], unique=False)
    op.create_index(op.f('ix_yccompany_nonprofit'), 'yccompany', ['nonprofit'], unique=False)
    op.create_index(op.f('ix_yccompany_slug'), 'yccompany', ['slug'], unique=False)
    op.create_index(op.f('ix_yccompany_status'), 'yccompany', ['status'], unique=False)
    op.create_index(op.f('ix_yccompany_team_size'), 'yccompany', ['team_size'], unique=False)
    op.create_index(op.f('ix_yccompany_top_company'), 'yccompany', ['top_company'], unique=False)
    op.create_index(op.f('ix_yccompany_updated_at'), 'yccompany', ['updated_at'], unique=False)
    op.create_index(op.f('ix_yccompany_yc_id'), 'yccompany', ['yc_id'], unique=True)
    op.create_index(op.f('ix_yccompany_year'), 'yccompany', ['year'], unique=False)
    op.create_table('ycsyncstate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('last_item_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ycsyncstate_source'), 'ycsyncstate', ['source'], unique=True)
    op.add_column('user', sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False))
    op.add_column('user', sa.Column('balance_cents', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_balance_cents'), 'user', ['balance_cents'], unique=False)
    op.create_index(op.f('ix_user_plan'), 'user', ['plan'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_plan'), table_name='user')
    op.drop_index(op.f('ix_user_balance_cents'), table_name='user')
    op.drop_column('user', 'balance_cents')
    op.drop_column('user', 'plan')
    op.drop_index(op.f('ix_ycsyncstate_source'), table_name='ycsyncstate')
    op.drop_table('ycsyncstate')
    op.drop_index(op.f('ix_yccompany_year'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_yc_id'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_updated_at'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_top_company'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_team_size'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_status'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_slug'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_nonprofit'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_name'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_launched_at'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_is_hiring'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_industry'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_created_at'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_batch_code'), table_name='yccompany')
    op.drop_index(op.f('ix_yccompany_batch'), table_name='yccompany')
    op.drop_table('yccompany')
    # ### end Alembic commands ###
