"""Added ycfounder

Revision ID: 66d036a8789e
Revises: 61d1928de416
Create Date: 2026-02-10 12:32:42.361941

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '66d036a8789e'
down_revision = '61d1928de416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ycfounder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('yc_profile_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('twitter_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['yccompany.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ycfounder_company_id'), 'ycfounder', ['company_id'], unique=False)
    op.create_index(op.f('ix_ycfounder_created_at'), 'ycfounder', ['created_at'], unique=False)
    op.create_index(op.f('ix_ycfounder_name'), 'ycfounder', ['name'], unique=False)
    op.create_index(op.f('ix_ycfounder_sort_order'), 'ycfounder', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ycfounder_sort_order'), table_name='ycfounder')
    op.drop_index(op.f('ix_ycfounder_name'), table_name='ycfounder')
    op.drop_index(op.f('ix_ycfounder_created_at'), table_name='ycfounder')
    op.drop_index(op.f('ix_ycfounder_company_id'), table_name='ycfounder')
    op.drop_table('ycfounder')
    # ### end Alembic commands ###
