/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as YcRouteImport } from './app/routes/yc'
import { Route as HealthRouteImport } from './app/routes/health'
import { Route as AdminRouteImport } from './app/routes/admin'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as UsersMeRouteImport } from './app/routes/users.me'
import { Route as AuthSignupRouteImport } from './app/routes/auth.signup'
import { Route as AuthSessionsRouteImport } from './app/routes/auth.sessions'
import { Route as AuthResetPasswordRouteImport } from './app/routes/auth.reset-password'
import { Route as AuthRecoverPasswordRouteImport } from './app/routes/auth.recover-password'
import { Route as AuthLoginRouteImport } from './app/routes/auth.login'
import { Route as AuthCompleteSignupRouteImport } from './app/routes/auth.complete-signup'
import { Route as AdminIndexRouteImport } from './app/routes/admin.index'
import { Route as AdminYcSyncRouteImport } from './app/routes/admin.yc-sync'
import { Route as AdminUsersRouteImport } from './app/routes/admin.users'

const YcRoute = YcRouteImport.update({
  id: '/yc',
  path: '/yc',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersMeRoute = UsersMeRouteImport.update({
  id: '/users/me',
  path: '/users/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSessionsRoute = AuthSessionsRouteImport.update({
  id: '/auth/sessions',
  path: '/auth/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverPasswordRoute = AuthRecoverPasswordRouteImport.update({
  id: '/auth/recover-password',
  path: '/auth/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteSignupRoute = AuthCompleteSignupRouteImport.update({
  id: '/auth/complete-signup',
  path: '/auth/complete-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminYcSyncRoute = AdminYcSyncRouteImport.update({
  id: '/yc-sync',
  path: '/yc-sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/health': typeof HealthRoute
  '/yc': typeof YcRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/yc-sync': typeof AdminYcSyncRoute
  '/auth/complete-signup': typeof AuthCompleteSignupRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sessions': typeof AuthSessionsRoute
  '/auth/signup': typeof AuthSignupRoute
  '/users/me': typeof UsersMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/health': typeof HealthRoute
  '/yc': typeof YcRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/yc-sync': typeof AdminYcSyncRoute
  '/auth/complete-signup': typeof AuthCompleteSignupRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sessions': typeof AuthSessionsRoute
  '/auth/signup': typeof AuthSignupRoute
  '/users/me': typeof UsersMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/health': typeof HealthRoute
  '/yc': typeof YcRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/yc-sync': typeof AdminYcSyncRoute
  '/auth/complete-signup': typeof AuthCompleteSignupRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sessions': typeof AuthSessionsRoute
  '/auth/signup': typeof AuthSignupRoute
  '/users/me': typeof UsersMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/health'
    | '/yc'
    | '/admin/users'
    | '/admin/yc-sync'
    | '/auth/complete-signup'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/auth/sessions'
    | '/auth/signup'
    | '/users/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/health'
    | '/yc'
    | '/admin/users'
    | '/admin/yc-sync'
    | '/auth/complete-signup'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/auth/sessions'
    | '/auth/signup'
    | '/users/me'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/health'
    | '/yc'
    | '/admin/users'
    | '/admin/yc-sync'
    | '/auth/complete-signup'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/auth/sessions'
    | '/auth/signup'
    | '/users/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HealthRoute: typeof HealthRoute
  YcRoute: typeof YcRoute
  AuthCompleteSignupRoute: typeof AuthCompleteSignupRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSessionsRoute: typeof AuthSessionsRoute
  AuthSignupRoute: typeof AuthSignupRoute
  UsersMeRoute: typeof UsersMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yc': {
      id: '/yc'
      path: '/yc'
      fullPath: '/yc'
      preLoaderRoute: typeof YcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/me': {
      id: '/users/me'
      path: '/users/me'
      fullPath: '/users/me'
      preLoaderRoute: typeof UsersMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sessions': {
      id: '/auth/sessions'
      path: '/auth/sessions'
      fullPath: '/auth/sessions'
      preLoaderRoute: typeof AuthSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover-password': {
      id: '/auth/recover-password'
      path: '/auth/recover-password'
      fullPath: '/auth/recover-password'
      preLoaderRoute: typeof AuthRecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-signup': {
      id: '/auth/complete-signup'
      path: '/auth/complete-signup'
      fullPath: '/auth/complete-signup'
      preLoaderRoute: typeof AuthCompleteSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/yc-sync': {
      id: '/admin/yc-sync'
      path: '/yc-sync'
      fullPath: '/admin/yc-sync'
      preLoaderRoute: typeof AdminYcSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminYcSyncRoute: typeof AdminYcSyncRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminYcSyncRoute: AdminYcSyncRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HealthRoute: HealthRoute,
  YcRoute: YcRoute,
  AuthCompleteSignupRoute: AuthCompleteSignupRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSessionsRoute: AuthSessionsRoute,
  AuthSignupRoute: AuthSignupRoute,
  UsersMeRoute: UsersMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
